### ISSUE TITLE
Feature request: highlight text to include in skeet and ability to edit before posting

### ISSUE THREAD

**Issue by aneeshsathe** [joneslloyd/bluniversal-comments#1]

**Comment by adamatic-me** [comment]
I love the highlight text idea!

**Comment by joneslloyd** [comment]
I am going to classify this as "_Won't do_", because:

The idea of this browser extension is to allow people to "Comment on a web page", as if it were a comments section beneath an article.

With that in mind, from a product perspective, I'd expect some sort of meaningful comment / reflection on the page's content, rather than quoting an aspect of the page as the content.

Also based on closer reading of your comment, it appears that this is in relation to the initial post of the web page. This is no longer handled by the user account that first uses the extension on a web page, but instead [a bot](https://bsky.app/profile/bluniversal.bsky.social).
